export {
  PACKAGE_ID,
  SOURCE_VERSION,
  FAN_2026_CITATION,
  FAN_2026_DOI,
  FIRE_SEASON_SHIFT_BY_BIOME,
  MADAKUMBURA_2025_CITATION,
  MADAKUMBURA_2025_DOI,
  CALIFORNIA_ONSET_ADVANCE_MIN_DAYS,
  CALIFORNIA_ONSET_ADVANCE_MAX_DAYS,
  CALIFORNIA_ECOREGIONS_AFFECTED,
  CALIFORNIA_ECOREGIONS_TOTAL,
  CALIFORNIA_STUDY_PERIOD,
  ZHU_2025_CITATION,
  ZHU_2025_DOI,
  SMOKE_AEROSOL_REGIONS_STUDIED,
  CALVO_SANCHO_2026_CITATION,
  CALVO_SANCHO_2026_DOI,
  HOURLY_RAINFALL_INTENSITY_INCREASE_PCT_PER_DEGC,
  SIX_HOUR_RAINFALL_RATE_INCREASE_PCT,
  AREA_ABOVE_180MM_RAINFALL_INCREASE_PCT,
  CATCHMENT_RAINFALL_VOLUME_INCREASE_PCT,
  CLAUSIUS_CLAPEYRON_BASELINE_PCT_PER_DEGC,
  MECHANISM_BREAKDOWN_PCT,
  KANG_2025_CITATION,
  KANG_2025_DOI,
  PRE_FIRE_FLOOD_PROBABILITY,
  POST_MEGAFIRE_FLOOD_PROBABILITY,
  MEGAFIRE_YEARS_STUDIED,
  STREAMFLOW_RECORD_YEARS,
  HAWKER_2026_CITATION,
  HAWKER_2026_DOI,
  FLOOD_EXTENT_UNDERESTIMATION_RANGE_PCT,
  POPULATION_EXPOSURE_UNDERESTIMATION_RANGE_PCT,
  HAWKER_STUDY_AREA_SQ_MILES,
  AZADGAR_2026_CITATION,
  AZADGAR_2026_DOI,
  SEALING_CITIES_STUDIED,
  SEALING_STUDY_PERIOD,
  SEALING_INDEX_NAMES,
  GLACIER_BUFFER_CROSS_REFERENCE_PACKAGE,
  GLACIER_BUFFER_CROSS_REFERENCE_PACKAGE_ID,
  GLACIER_BUFFER_CROSS_REFERENCE_CITATION,
  CASCADE_LINKS,
} from "./constants.ts";

export {
  ALL_EVIDENCE,
  onsetEvidence,
  precipitationEvidence,
  amplificationEvidence,
  hasMultipleCascadeStages,
  fireSeasonShiftByBiome,
  isShiftDirectionUniformGlobally,
  californiaOnsetAdvanceRangeDays,
  californiaEcoregionsAffectedFraction,
  californiaStudyPeriod,
  regionsStudiedCount,
  doesSmokeDelayPrecipitationOnset,
  isEffectClaimedGloballyUniform,
  hourlyRainfallIntensityIncreasePctPerDegc,
  exceedsClausiusClapeyronScaling,
  mechanismBreakdownPct,
  eventNameAndDate,
  sixHourRainfallRateIncreasePct,
  areaAbove180mmRainfallIncreasePct,
  catchmentRainfallVolumeIncreasePct,
  preFireFloodProbability,
  postMegafireFloodProbability,
  floodProbabilityIncreaseFactor,
  isMechanismSoilHydrophobicity,
  megafireYearsStudied,
  streamflowRecordLengthYears,
  floodExtentUnderestimationRangePct,
  populationExposureUnderestimationRangePct,
  isChannelChangeEffectComparableToClimateChange,
  studyAreaSqMiles,
  citiesStudied,
  sealingStudyPeriod,
  indexNames,
  doesLandTakeReduceStormwaterRetentionCapacity,
  combinedCascadeDescription,
  isCombinedCascadeADirectlyStudiedSingleSystem,
  componentMechanismsIndependentlyVerified,
  numberOfCascadeLinks,
  glacierBufferCrossReference,
  type EvidenceEntry,
  type Stance,
} from "./evidence.ts";

export {
  STANCE_LABEL_DE,
  EVIDENCE_DOI,
  EVIDENCE_URL,
  KEY_NUMBERS,
  stanceLabelDe,
  headlineFor,
} from "./display.ts";
